# Generated by Django 4.2.7 on 2023-11-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_orderphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Oczekujące'), ('Completed', 'Zrealizowane'), ('Needs Review', 'Do poprawy')], default='Pending', max_length=20),
        ),
    ]
