# Generated by Django 4.2.7 on 2023-11-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
